name: action1

on:
  push:
    branches:
     - '*'
     - 'feature/*'
  pull_request:
    branches:
     - '*'
     - 'feature/*'

jobs:
  print_hi:
    runs-on: ubuntu-latest

    steps:
      - name: say hi
        run: echo Hi!